### ISSUE TITLE
Tries to open everything with a browser

### ISSUE THREAD

**Issue by averms** [arp242/xdg_open.vim#1]
When I edit a file and press gx on something like
```
/home/user/picture.png
```
Chrome opens a new tab and with `home/user/picture.png`. I did some debugging and I found out that the xdg open command that runs is
```
xdg-open http:///home/user/picture.png
```

I have a fork that fixes this and a few other things. Let me know if you want me to clean it up and open a pull req.

**Comment by arp242** [comment]
Yeah, the main use case I made it for is opening stuff in the browser. PRs always welcome!

**Comment by arp242** [comment]
I spent some time on this today, and this should be fixed now; `gx` always opens a path, and `gX` always an URL. This allows both opening local files and URLs like `example.com/path`.
