### ISSUE TITLE
Some Markdown URLs

### ISSUE THREAD

**Issue by igorgue** [arp242/xdg_open.vim#7]
Hi, thanks for the plugin, it's works great with qs strings. And since I use another file manager, I can disable netrw completely with it.

Now, on markdown I have something like this:

```md
[xdg_open.vim](https://github.com/arp242/xdg_open.vim)
```

Unfortunately `cWord` considers `()` part of the object so it cannot open it.

**Comment by arp242** [comment]
This should work correct if the `filetype` is set to `markdown`. I added some special-fu for this a few months ago: https://github.com/arp242/xdg_open.vim/commit/3764230e14c2a0042b5462c2c85eb3c4f40b24af#diff-cf9ae36af89d92afdb38494cdf221fb2f7a3a441d57c9a21deb4ebd6176165fcR46

Seems to work if I test it.

**Comment by arp242** [comment]
I did just notice it didn't work quite correct if there are spaces in the description; fixed that in 7832be894. Maybe that's the problem you ran in to? Or maybe you were using an older version from before I added Markdown?

Closing for now as it seems correct, but let me know if there's still an issue and I can fix it.

**Comment by igorgue** [comment]
I'll update an test, thank you so much! This is the plug-in that works with Neovim Noice to make UI super duper cool, but disables regular gx
